service: "crypto-api"
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  regions: us-east

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'